wrange: 3000. 10000.
vmicro: -1
ncpu: 16
nmerge: 100
keepingz: False
grids: ['f_k1','f_k2','f_k3']
f_k1:
       type: 'mkk-irregular'
       nmodels: 3000
       pteff: 3000.   6700.
       plogg: -1.0     5.5
       pfeh:  -2.5     1.0
f_k2:
       type: 'mkk-irregular'
       nmodels: 2000
       pteff: 6750.    10500.
       plogg: 1.0      5.5
       pfeh:   8      -2.5
f_k3:
       type: 'mkk-irregular'
       nmodels: 1000
       pteff: 11000.  30000.
       plogg: 2.0      5.5
       pfeh: -2.5      1.0
